spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/projects/springboot/cloud-config
          
server:
  port: 8888
management:
  context-path: /admin
  
security:
  user:
    password: s3cret
 