spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/simon-wilkins/cloud-config
          
server:
  port: 8888
management:
  context-path: /admin
  
security:
  user:
    password: '{cipher}ca975af0e265d0d8e572b88fa7812cd9d5b3bb200ded2082b1c64e0dcf7364e4'
 